### ISSUE TITLE
Reading player files is incredibly slow

### ISSUE THREAD

**Issue by DaftLad** [medeor413/starcheat#23]
It takes about 4 to 8 minutes for Starcheat to finish reading player files.
I only have two characters, and I've tried to clear their inventories and getting rid of any custom items they have on them, along with removing all mods I have to see if it made it read any faster. No dice.
I've linked others this version of Starcheat and they have no issues with it. What's going on here?

**Comment by rubellyte** [comment]
Can you provide a log file for me? Also a list of any mods you have installed would be helpful.
That's very unusual for loading time, I have extremely large player files and it only takes me 30 seconds or so to load.

**Comment by DaftLad** [comment]
[starcheat.txt](https://github.com/medeor413/starcheat/files/386931/starcheat.txt)
This is without any mods. The mods I used before was Extra Zoom Levels, Manipulated UI, Infinite Reach, Spawnable Item Pack and Wardrobe.

**Comment by rubellyte** [comment]
Wow, shit. There's nothing unusual happening in there, so I really have no idea what's going on here.

**Comment by DaftLad** [comment]
It's strange that this is happening in the first place, since I had no issues with the older version of Starcheat, the one for Glad Giraffe.
Though, wizzomafizzo mentioned something about "this implementation and py-starbound" on another issue. https://github.com/wizzomafizzo/starcheat/issues/282
I'm no coder or programmer, but maybe that's got something to do with it? Just a wild guess.

**Comment by kurisubrooks** [comment]
Hi, could we please have your .player files for testing? We'd like to find out the cause of this.

**Comment by DaftLad** [comment]
[Player Files.zip](https://github.com/medeor413/starcheat/files/387312/Player.Files.zip)
Here you go.

**Comment by rubellyte** [comment]
Alright so I loaded up your player files and can confirm it takes a stupidly long time. It looks like the issue is that your player file contains approximately 111,000 (!) lines of blueprints. It looks like the wait time is from Starcheat loading the files into memory and converting them to JSON for editing, and it has to convert said 111,000 lines, which takes a while. I unfortunately don't think I can do anything about this.

**Comment by wizzomafizzo** [comment]
is there a loading bar or some kind of notification during this load? i doubt it can be sped up but i've found showing the user that _something_ is happening goes a long way to make things seem faster

**Comment by kurisubrooks** [comment]
There's a loading bar when loading the player files
![image](https://cloud.githubusercontent.com/assets/6291467/17234493/ec7c6f22-557c-11e6-8ccf-567ec1f79941.png)

There's also one when loading the .player file into the program
![image](https://cloud.githubusercontent.com/assets/6291467/17234503/fb41febe-557c-11e6-97bf-1e3bec12ebf5.png)
