### ISSUE TITLE
No player files detected? 

### ISSUE THREAD

**Issue by IngloriouslyBad** [medeor413/starcheat#25]
When I run star cheat I receive a pop up that says: No player files dected. Reselect the Starbound Folder? 

The folder that was detected by starcheat as the correct folder: C:\Program Files (x86)\Steam\SteamApps\common\Starbound

Continually get the same message. So I manually selected the starbound folder, got the same message.

**Comment by kurisubrooks** [comment]
Hi, could you please provide us with the log file? It will give us the debug information as to why this might be happening.

The log file is located in `%appdata%/starcheat/starcheat.log`

**Comment by chrmoritz** [comment]
Did you created and saved at least one character with the new Starbound 1.0 version?

**Comment by rubellyte** [comment]
Closing because no response in over a month.
