### ISSUE TITLE
Starcheat Deleted Savefile (kind of)

### ISSUE THREAD

**Issue by Kadawie** [medeor413/starcheat#26]
After using Starcheat and launching the game my savefiles were no longer avaible in the character selection screen. Yet I am still able to load my personal character with Starcheat.

**Comment by kurisubrooks** [comment]
Hi. It sounds to me like you corrupted your .player file. If you can still open your .player in Starcheat, please undo the changes, save, and check if you're now able to use your player in Starbound.
